# Generated by Django 5.0.14 on 2026-03-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_audit_risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditScreeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditor_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('closed', 'Closed')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Temp files are deleted after this time if not already finished.')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('screening_summary', models.TextField(blank=True, help_text='Summary of screening results (kept; files are not).')),
                ('auditor_notes', models.TextField(blank=True, help_text='Auditor notes from the screening (kept).')),
                ('risk_flags', models.JSONField(blank=True, default=list, help_text='Detected risk indicators from screening (kept).')),
                ('transaction_references', models.JSONField(blank=True, default=list, help_text='References to transactions or items noted during screening.')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_sessions', to='tenant_audit_risk.investigationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_file_path', models.CharField(db_index=True, max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='tenant_audit_risk.auditscreeningsession')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditscreeningsession',
            index=models.Index(fields=['status'], name='tenant_audi_status_27994a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditscreeningsession',
            index=models.Index(fields=['expires_at'], name='tenant_audi_expires_467702_idx'),
        ),
    ]
