# Generated by Django 5.0.14 on 2026-03-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_audit_risk', '0002_screening_upload_temp_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, max_length=80)),
                ('source_id', models.PositiveIntegerField(db_index=True)),
                ('assigned_to_id', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='tenant_audit_risk.riskalert'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='donor_project_impact',
            field=models.TextField(blank=True, help_text='Description of impact on donor(s) or project(s).'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='financial_impact',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='finding_stage',
            field=models.CharField(choices=[('preliminary', 'Preliminary'), ('confirmed', 'Confirmed'), ('realized', 'Realized')], db_index=True, default='preliminary', help_text='Preliminary (under review), Confirmed (validated), Realized (impact materialized).', max_length=20),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='is_actual',
            field=models.BooleanField(default=False, help_text='Whether the finding is an actual finding (true) or a false positive.'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='is_realized',
            field=models.BooleanField(default=False, help_text='Whether financial or other impact has been realized.'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='management_action',
            field=models.TextField(blank=True, help_text='Actions taken or planned by management.'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='realized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='recovered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='recovery_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('partial', 'Partially recovered'), ('recovered', 'Recovered'), ('written_off', 'Written off'), ('n_a', 'N/A')], db_index=True, default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='root_cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='unrecovered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Outstanding exposure (financial_impact minus recovered).', max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['finding_stage'], name='tenant_audi_finding_8a59ab_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['is_realized'], name='tenant_audi_is_real_464c37_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['recovery_status'], name='tenant_audi_recover_8ca89a_idx'),
        ),
        migrations.AddField(
            model_name='auditcorrectionrequest',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_requests', to='tenant_audit_risk.auditfinding'),
        ),
        migrations.AddIndex(
            model_name='auditcorrectionrequest',
            index=models.Index(fields=['assigned_to_id', 'status'], name='tenant_audi_assigne_1a638a_idx'),
        ),
    ]
