# Generated by Django 5.0.14 on 2026-03-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_audit_risk', '0003_finding_lifecycle_and_impact'),
        ('tenant_grants', '0020_financial_setup_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskalert',
            name='amount_affected',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='assigned_to_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='control_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='tenant_audit_risk.controlrule'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_violation_alerts', to='tenant_grants.grant'),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='module',
            field=models.CharField(blank=True, help_text='Module e.g. Finance, Procurement.', max_length=80),
        ),
        migrations.AddField(
            model_name='riskalert',
            name='violation_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('under_review', 'Under review'), ('correction_requested', 'Correction requested'), ('corrected', 'Corrected'), ('revalidated', 'Revalidated'), ('closed', 'Closed')], db_index=True, help_text='Workflow status for control violations.', max_length=24, null=True),
        ),
        migrations.AddIndex(
            model_name='riskalert',
            index=models.Index(fields=['violation_status'], name='tenant_audi_violati_cbe29f_idx'),
        ),
    ]
