# Generated by Django 5.0.14 on 2026-03-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_audit_risk', '0004_control_violation_register_fields'),
        ('tenant_grants', '0020_financial_setup_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionriskassessment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='transactionriskassessment',
            name='assigned_to_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionriskassessment',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='tenant_grants.grant'),
        ),
        migrations.AddField(
            model_name='transactionriskassessment',
            name='investigation_status',
            field=models.CharField(choices=[('detected', 'Detected'), ('under_review', 'Under review'), ('cleared', 'Cleared'), ('correction_requested', 'Correction requested'), ('converted_to_finding', 'Converted to finding'), ('closed', 'Closed')], db_index=True, default='detected', max_length=24),
        ),
        migrations.AddField(
            model_name='transactionriskassessment',
            name='module',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transactionriskassessment',
            name='vendor_display',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='transactionriskassessment',
            index=models.Index(fields=['investigation_status'], name='tenant_audi_investi_b6a0d8_idx'),
        ),
    ]
