# Generated by Django 5.0.14 on 2026-03-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_grants', '0001_initial'),
        ('tenant_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grant_approval_decisions', to='tenant_users.tenantuser')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tenant_grants.grant')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_approval_requests', to='tenant_users.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
