# Generated by Django 5.0.14 on 2026-03-14 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_grants', '0019_procurement_management'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['name'], 'verbose_name': 'Donor (Register)'},
        ),
        migrations.RemoveConstraint(
            model_name='goodsreceipt',
            name='tenant_grants_gr_po_gr_number_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='goodsreceiptline',
            name='tenant_grants_grline_gr_po_line_uniq',
        ),
        migrations.AlterField(
            model_name='donorrestriction',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_restriction_records', to='tenant_grants.grant'),
        ),
        migrations.AlterField(
            model_name='granttracking',
            name='grant_type',
            field=models.CharField(blank=True, choices=[('institutional', 'Institutional Grant'), ('project', 'Project Grant'), ('emergency', 'Emergency Grant'), ('core', 'Core Funding'), ('sub_grant', 'Sub-Grant'), ('multi_donor', 'Multi-Donor Grant'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='granttracking',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='procurement_method',
            field=models.CharField(choices=[('open_tender', 'Open Tender'), ('request_quotation', 'Request for Quotation'), ('direct_purchase', 'Direct Purchase'), ('framework', 'Framework Agreement'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceipt',
            unique_together={('po', 'gr_number')},
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptline',
            unique_together={('gr', 'po_line')},
        ),
    ]
