# Generated by Django 5.0.14 on 2026-03-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0012_chart_account_audit_and_statement_type'),
        ('tenant_grants', '0020_financial_setup_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='tenant_finance.currency'),
        ),
        migrations.AddField(
            model_name='grant',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Grant must belong to a project for transaction posting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='tenant_grants.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tenant_grants.donor'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
