# Generated by Django 5.0.14 on 2026-03-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_grants', '0021_project_donor_dates_grant_project_currency'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects_managed', to='tenant_users.tenantuser'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On hold'), ('closed', 'Closed'), ('completed', 'Completed')], db_index=True, default='planning', max_length=20),
        ),
    ]
