# Generated by Django 5.0.14 on 2026-03-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0043_project_master_registry_fields'),
        ('tenant_grants', '0023_project_grant_period_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Default reporting currency when multiple grants use different currencies.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='tenant_finance.currency'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_type',
            field=models.CharField(blank=True, choices=[('project', 'Project grant'), ('core', 'Core / institutional'), ('emergency', 'Emergency'), ('institutional', 'Institutional'), ('other', 'Other')], help_text='Primary funding modality for this project (optional).', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, help_text='Primary implementation location (region, site, or country).', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='program_sector',
            field=models.CharField(blank=True, help_text='Program, sector, or thematic area.', max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='total_beneficiaries',
            field=models.PositiveIntegerField(default=0, help_text='Planned or reported beneficiaries (summary field).'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On hold'), ('closed', 'Closed'), ('completed', 'Completed')], db_index=True, default='planning', max_length=20),
        ),
    ]
