# Generated by Django 5.0.14 on 2026-03-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_grants", "0028_reporting_deadline_enterprise"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrantBudget",
            fields=[],
            options={
                "verbose_name": "Grant budget",
                "verbose_name_plural": "Grant budgets",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tenant_grants.grant",),
        ),
        migrations.CreateModel(
            name="GrantBudgetLine",
            fields=[],
            options={
                "verbose_name": "Grant budget line",
                "verbose_name_plural": "Grant budget lines",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tenant_grants.budgetline",),
        ),
    ]
