# Donor validation: audit fields, country ISO list, currency FK, donor_type required.
# Data migration: legacy country text -> alpha-2; legacy currency string -> Currency FK.

import django.db.models.deletion
from django.db import migrations, models


def forwards_country(apps, schema_editor):
    Donor = apps.get_model("tenant_grants", "Donor")
    from tenant_grants.donor_countries import normalize_legacy_country

    db_alias = schema_editor.connection.alias
    for d in Donor.objects.using(db_alias).all():
        raw = getattr(d, "country", None) or ""
        if not raw:
            continue
        nc = normalize_legacy_country(str(raw))
        if str(raw).strip() != nc:
            Donor.objects.using(db_alias).filter(pk=d.pk).update(country=nc)


def forwards_currency_fk(apps, schema_editor):
    Donor = apps.get_model("tenant_grants", "Donor")
    Currency = apps.get_model("tenant_finance", "Currency")
    db_alias = schema_editor.connection.alias
    for d in Donor.objects.using(db_alias).all():
        legacy = getattr(d, "preferred_currency_legacy", None) or ""
        legacy = (legacy or "").strip().upper()
        if not legacy:
            continue
        if len(legacy) > 3:
            legacy = legacy[:3]
        cur = Currency.objects.using(db_alias).filter(code__iexact=legacy).first()
        if cur:
            Donor.objects.using(db_alias).filter(pk=d.pk).update(preferred_currency_id=cur.pk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_finance", "0050_journalentry_receipt_stream"),
        ("tenant_grants", "0032_grant_funding_modality"),
        ("tenant_users", "0004_add_totp_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donors_created",
                to="tenant_users.tenantuser",
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donors_updated",
                to="tenant_users.tenantuser",
            ),
        ),
        migrations.RenameField(
            model_name="donor",
            old_name="preferred_currency",
            new_name="preferred_currency_legacy",
        ),
        migrations.AddField(
            model_name="donor",
            name="preferred_currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Must be a currency from the system currency list.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="donors_preferred",
                to="tenant_finance.currency",
            ),
        ),
        migrations.RunPython(forwards_currency_fk, noop_reverse),
        migrations.RemoveField(
            model_name="donor",
            name="preferred_currency_legacy",
        ),
        migrations.RunPython(forwards_country, noop_reverse),
        migrations.AlterField(
            model_name="donor",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AF", "Afghanistan"),
                    ("AX", "Åland Islands"),
                    ("AL", "Albania"),
                    ("DZ", "Algeria"),
                    ("AS", "American Samoa"),
                    ("AD", "Andorra"),
                    ("AO", "Angola"),
                    ("AI", "Anguilla"),
                    ("AQ", "Antarctica"),
                    ("AG", "Antigua and Barbuda"),
                    ("AR", "Argentina"),
                    ("AM", "Armenia"),
                    ("AW", "Aruba"),
                    ("AU", "Australia"),
                    ("AT", "Austria"),
                    ("AZ", "Azerbaijan"),
                    ("BS", "Bahamas"),
                    ("BH", "Bahrain"),
                    ("BD", "Bangladesh"),
                    ("BB", "Barbados"),
                    ("BY", "Belarus"),
                    ("BE", "Belgium"),
                    ("BZ", "Belize"),
                    ("BJ", "Benin"),
                    ("BM", "Bermuda"),
                    ("BT", "Bhutan"),
                    ("BO", "Bolivia"),
                    ("BQ", "Bonaire, Sint Eustatius and Saba"),
                    ("BA", "Bosnia and Herzegovina"),
                    ("BW", "Botswana"),
                    ("BV", "Bouvet Island"),
                    ("BR", "Brazil"),
                    ("IO", "British Indian Ocean Territory"),
                    ("BN", "Brunei Darussalam"),
                    ("BG", "Bulgaria"),
                    ("BF", "Burkina Faso"),
                    ("BI", "Burundi"),
                    ("CV", "Cabo Verde"),
                    ("KH", "Cambodia"),
                    ("CM", "Cameroon"),
                    ("CA", "Canada"),
                    ("KY", "Cayman Islands"),
                    ("CF", "Central African Republic"),
                    ("TD", "Chad"),
                    ("CL", "Chile"),
                    ("CN", "China"),
                    ("CX", "Christmas Island"),
                    ("CC", "Cocos (Keeling) Islands"),
                    ("CO", "Colombia"),
                    ("KM", "Comoros"),
                    ("CG", "Congo"),
                    ("CD", "Congo, Democratic Republic of the"),
                    ("CK", "Cook Islands"),
                    ("CR", "Costa Rica"),
                    ("CI", "Côte d'Ivoire"),
                    ("HR", "Croatia"),
                    ("CU", "Cuba"),
                    ("CW", "Curaçao"),
                    ("CY", "Cyprus"),
                    ("CZ", "Czechia"),
                    ("DK", "Denmark"),
                    ("DJ", "Djibouti"),
                    ("DM", "Dominica"),
                    ("DO", "Dominican Republic"),
                    ("EC", "Ecuador"),
                    ("EG", "Egypt"),
                    ("SV", "El Salvador"),
                    ("GQ", "Equatorial Guinea"),
                    ("ER", "Eritrea"),
                    ("EE", "Estonia"),
                    ("SZ", "Eswatini"),
                    ("ET", "Ethiopia"),
                    ("FK", "Falkland Islands (Malvinas)"),
                    ("FO", "Faroe Islands"),
                    ("FJ", "Fiji"),
                    ("FI", "Finland"),
                    ("FR", "France"),
                    ("GF", "French Guiana"),
                    ("PF", "French Polynesia"),
                    ("TF", "French Southern Territories"),
                    ("GA", "Gabon"),
                    ("GM", "Gambia"),
                    ("GE", "Georgia"),
                    ("DE", "Germany"),
                    ("GH", "Ghana"),
                    ("GI", "Gibraltar"),
                    ("GR", "Greece"),
                    ("GL", "Greenland"),
                    ("GD", "Grenada"),
                    ("GP", "Guadeloupe"),
                    ("GU", "Guam"),
                    ("GT", "Guatemala"),
                    ("GG", "Guernsey"),
                    ("GN", "Guinea"),
                    ("GW", "Guinea-Bissau"),
                    ("GY", "Guyana"),
                    ("HT", "Haiti"),
                    ("HM", "Heard Island and McDonald Islands"),
                    ("VA", "Holy See"),
                    ("HN", "Honduras"),
                    ("HK", "Hong Kong"),
                    ("HU", "Hungary"),
                    ("IS", "Iceland"),
                    ("IN", "India"),
                    ("ID", "Indonesia"),
                    ("IR", "Iran"),
                    ("IQ", "Iraq"),
                    ("IE", "Ireland"),
                    ("IM", "Isle of Man"),
                    ("IL", "Israel"),
                    ("IT", "Italy"),
                    ("JM", "Jamaica"),
                    ("JP", "Japan"),
                    ("JE", "Jersey"),
                    ("JO", "Jordan"),
                    ("KZ", "Kazakhstan"),
                    ("KE", "Kenya"),
                    ("KI", "Kiribati"),
                    ("KP", "Korea, Democratic People's Republic of"),
                    ("KR", "Korea, Republic of"),
                    ("KW", "Kuwait"),
                    ("KG", "Kyrgyzstan"),
                    ("LA", "Lao People's Democratic Republic"),
                    ("LV", "Latvia"),
                    ("LB", "Lebanon"),
                    ("LS", "Lesotho"),
                    ("LR", "Liberia"),
                    ("LY", "Libya"),
                    ("LI", "Liechtenstein"),
                    ("LT", "Lithuania"),
                    ("LU", "Luxembourg"),
                    ("MO", "Macao"),
                    ("MG", "Madagascar"),
                    ("MW", "Malawi"),
                    ("MY", "Malaysia"),
                    ("MV", "Maldives"),
                    ("ML", "Mali"),
                    ("MT", "Malta"),
                    ("MH", "Marshall Islands"),
                    ("MQ", "Martinique"),
                    ("MR", "Mauritania"),
                    ("MU", "Mauritius"),
                    ("YT", "Mayotte"),
                    ("MX", "Mexico"),
                    ("FM", "Micronesia"),
                    ("MD", "Moldova"),
                    ("MC", "Monaco"),
                    ("MN", "Mongolia"),
                    ("ME", "Montenegro"),
                    ("MS", "Montserrat"),
                    ("MA", "Morocco"),
                    ("MZ", "Mozambique"),
                    ("MM", "Myanmar"),
                    ("NA", "Namibia"),
                    ("NR", "Nauru"),
                    ("NP", "Nepal"),
                    ("NL", "Netherlands"),
                    ("NC", "New Caledonia"),
                    ("NZ", "New Zealand"),
                    ("NI", "Nicaragua"),
                    ("NE", "Niger"),
                    ("NG", "Nigeria"),
                    ("NU", "Niue"),
                    ("NF", "Norfolk Island"),
                    ("MK", "North Macedonia"),
                    ("MP", "Northern Mariana Islands"),
                    ("NO", "Norway"),
                    ("OM", "Oman"),
                    ("PK", "Pakistan"),
                    ("PW", "Palau"),
                    ("PS", "Palestine, State of"),
                    ("PA", "Panama"),
                    ("PG", "Papua New Guinea"),
                    ("PY", "Paraguay"),
                    ("PE", "Peru"),
                    ("PH", "Philippines"),
                    ("PN", "Pitcairn"),
                    ("PL", "Poland"),
                    ("PT", "Portugal"),
                    ("PR", "Puerto Rico"),
                    ("QA", "Qatar"),
                    ("RE", "Réunion"),
                    ("RO", "Romania"),
                    ("RU", "Russian Federation"),
                    ("RW", "Rwanda"),
                    ("BL", "Saint Barthélemy"),
                    ("SH", "Saint Helena, Ascension and Tristan da Cunha"),
                    ("KN", "Saint Kitts and Nevis"),
                    ("LC", "Saint Lucia"),
                    ("MF", "Saint Martin (French part)"),
                    ("PM", "Saint Pierre and Miquelon"),
                    ("VC", "Saint Vincent and the Grenadines"),
                    ("WS", "Samoa"),
                    ("SM", "San Marino"),
                    ("ST", "Sao Tome and Principe"),
                    ("SA", "Saudi Arabia"),
                    ("SN", "Senegal"),
                    ("RS", "Serbia"),
                    ("SC", "Seychelles"),
                    ("SL", "Sierra Leone"),
                    ("SG", "Singapore"),
                    ("SX", "Sint Maarten (Dutch part)"),
                    ("SK", "Slovakia"),
                    ("SI", "Slovenia"),
                    ("SB", "Solomon Islands"),
                    ("SO", "Somalia"),
                    ("ZA", "South Africa"),
                    ("GS", "South Georgia and the South Sandwich Islands"),
                    ("SS", "South Sudan"),
                    ("ES", "Spain"),
                    ("LK", "Sri Lanka"),
                    ("SD", "Sudan"),
                    ("SR", "Suriname"),
                    ("SJ", "Svalbard and Jan Mayen"),
                    ("SE", "Sweden"),
                    ("CH", "Switzerland"),
                    ("SY", "Syrian Arab Republic"),
                    ("TW", "Taiwan"),
                    ("TJ", "Tajikistan"),
                    ("TZ", "Tanzania"),
                    ("TH", "Thailand"),
                    ("TL", "Timor-Leste"),
                    ("TG", "Togo"),
                    ("TK", "Tokelau"),
                    ("TO", "Tonga"),
                    ("TT", "Trinidad and Tobago"),
                    ("TN", "Tunisia"),
                    ("TR", "Türkiye"),
                    ("TM", "Turkmenistan"),
                    ("TC", "Turks and Caicos Islands"),
                    ("TV", "Tuvalu"),
                    ("UG", "Uganda"),
                    ("UA", "Ukraine"),
                    ("AE", "United Arab Emirates"),
                    ("GB", "United Kingdom"),
                    ("US", "United States of America"),
                    ("UM", "United States Minor Outlying Islands"),
                    ("UY", "Uruguay"),
                    ("UZ", "Uzbekistan"),
                    ("VU", "Vanuatu"),
                    ("VE", "Venezuela"),
                    ("VN", "Viet Nam"),
                    ("VG", "Virgin Islands, British"),
                    ("VI", "Virgin Islands, U.S."),
                    ("WF", "Wallis and Futuna"),
                    ("EH", "Western Sahara"),
                    ("YE", "Yemen"),
                    ("ZM", "Zambia"),
                    ("ZW", "Zimbabwe"),
                ],
                help_text="ISO 3166-1 alpha-2 code from the predefined country list.",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_type",
            field=models.CharField(
                choices=[
                    ("institution", "Institution"),
                    ("government", "Government"),
                    ("private", "Private"),
                    ("foundation", "Foundation"),
                    ("corporate", "Corporate"),
                    ("other", "Other"),
                ],
                default="institution",
                max_length=20,
            ),
        ),
    ]
