# Generated by Django 5.0.14 on 2026-03-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_grants", "0034_funding_source_payment_modalities"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundingSourcePaymentStructure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("advance", "Advance"),
                            ("reimbursement", "Reimbursement"),
                            ("retention", "Retention"),
                            ("instalment", "Instalment"),
                            ("milestone_based", "Milestone based"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "payment_trigger",
                    models.CharField(
                        choices=[
                            ("agreement_signed", "Agreement signed"),
                            ("expense_report_approved", "Expense report approved"),
                            ("milestone_completed", "Milestone completed"),
                            ("final_audit_approved", "Final audit approved"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "funding_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_structure",
                        to="tenant_grants.fundingsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment structure line",
                "verbose_name_plural": "Payment structure",
                "ordering": ["funding_source", "sort_order", "id"],
            },
        ),
        migrations.AlterField(
            model_name="granttranche",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("advance", "Advance"),
                    ("reimbursement", "Reimbursement"),
                    ("retention", "Retention"),
                    ("instalment", "Instalment"),
                    ("milestone_based", "Milestone based"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="granttranche",
            name="trigger_condition",
            field=models.CharField(
                choices=[
                    ("contract_signing", "Agreement signed"),
                    ("expense_report_approval", "Expense report approved"),
                    ("audit_approval", "Final audit approved"),
                    ("milestone_completed", "Milestone completed"),
                ],
                max_length=40,
            ),
        ),
    ]
