# Generated by Django 5.0.14 on 2026-03-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_grants', '0035_mixed_modality_payment_structure'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fundingsourcepaymentstructure',
            constraint=models.UniqueConstraint(fields=('funding_source', 'sort_order'), name='uq_fs_payment_structure_order_per_modality'),
        ),
    ]
