# Generated by Django 5.0.14 on 2026-03-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0050_journalentry_receipt_stream'),
        ('tenant_grants', '0036_funding_structure_fk_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSourceComponentAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('advance', 'Advance'), ('reimbursement', 'Reimbursement'), ('retention', 'Retention'), ('instalment', 'Instalment'), ('milestone_based', 'Milestone based')], db_index=True, max_length=24)),
                ('bank_account_type', models.CharField(blank=True, default='', help_text='Preferred bank account type for this payment component (operating/project/restricted/petty_cash).', max_length=20)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_account_maps', to='tenant_grants.fundingsource')),
                ('income_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_modality_income_maps', to='tenant_finance.chartaccount')),
                ('receivable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_modality_receivable_maps', to='tenant_finance.chartaccount')),
            ],
            options={
                'ordering': ['funding_source', 'component_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='fundingsourcecomponentaccountmap',
            constraint=models.UniqueConstraint(fields=('funding_source', 'component_type'), name='uq_funding_source_component_account_map'),
        ),
    ]
