# Generated by Django 5.0.14 on 2026-03-28 05:40

from django.db import migrations, models


def forwards_move_dimension_codes_from_funding_type(apps, schema_editor):
    """Older forms stored program dimension codes in funding_type; move to program_category_code."""
    Project = apps.get_model("tenant_grants", "Project")
    ft_allowed = {"project", "core", "emergency", "institutional", "other"}
    for p in Project.objects.all().only("id", "funding_type", "program_category_code"):
        ft = (p.funding_type or "").strip()
        if not ft or ft in ft_allowed:
            continue
        p.program_category_code = ft
        p.funding_type = "project"
        p.save(update_fields=["program_category_code", "funding_type"])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_grants", "0038_fundingsourcecomponentaccountmap_missing_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="program_category_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Financial dimension value code for program category (e.g. PRG-01), when Program dimension is used.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="funding_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("project", "Project grant"),
                    ("core", "Core / institutional"),
                    ("emergency", "Emergency"),
                    ("institutional", "Institutional"),
                    ("other", "Other"),
                ],
                help_text="High-level funding category (project / core / …). Kept for reporting; program pick from dimensions is stored in program_category_code.",
                max_length=30,
            ),
        ),
        migrations.RunPython(forwards_move_dimension_codes_from_funding_type, backwards_noop),
    ]
