# Generated by Django 5.0.14 on 2026-03-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_grants", "0039_project_program_category_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetline",
            name="budget_line_code",
            field=models.CharField(
                help_text="Donor or internal budget line code (unique per grant); may differ from COA code.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="budgetline",
            name="category",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
