# Generated by Django 5.0.14 on 2026-03-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='approval_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='position',
            field=models.CharField(blank=True, help_text='Job title', max_length=120),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='preferred_language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='tenant_profiles/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='system_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='time_zone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TenantLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='tenant_users.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tenant_user_user_id_dadfec_idx')],
            },
        ),
    ]
