# Generated by Django 5.0.14 on 2026-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_grants', '0020_financial_setup_models'),
        ('tenant_users', '0002_profile_and_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='assigned_grants',
            field=models.ManyToManyField(blank=True, help_text='Grants/projects this user is assigned to.', related_name='assigned_users', to='tenant_grants.grant'),
        ),
    ]
