# Generated by Django 5.0.14 on 2026-03-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_users', '0003_user_assigned_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 TOTP secret for authenticator apps.', max_length=32),
        ),
    ]
