# Generated by Django 5.0.14 on 2026-04-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0011_tenant_branding_text_on_colors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(help_text='Full message; shown in banner, popup, and announcement panel.')),
                ('category', models.CharField(choices=[('system_update', 'System update'), ('billing', 'Billing'), ('security', 'Security'), ('general', 'General')], db_index=True, default='general', max_length=32)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=16)),
                ('targeting_mode', models.CharField(choices=[('all', 'All tenants'), ('selected', 'Selected tenants'), ('by_module', 'Tenants by module')], default='all', max_length=16)),
                ('start_at', models.DateTimeField(db_index=True, help_text='Announcement is visible from this time (inclusive).')),
                ('end_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional; leave empty for open-ended after start.', null=True)),
                ('send_email', models.BooleanField(default=False, help_text='Send email when published (requires mail configuration).')),
                ('show_popup', models.BooleanField(default=False)),
                ('show_dashboard_banner', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_announcements_created', to=settings.AUTH_USER_MODEL)),
                ('target_modules', models.ManyToManyField(blank=True, help_text='Used when targeting is «Tenants by module» (tenant has module enabled).', related_name='platform_announcements_by_module', to='tenants.module')),
                ('target_tenants', models.ManyToManyField(blank=True, help_text='Used when targeting is «Selected tenants».', related_name='platform_announcements_targeted', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-start_at', '-id'],
                'indexes': [models.Index(fields=['status', 'start_at', 'end_at'], name='platform_an_status_c26bff_idx')],
            },
        ),
    ]
