# Generated by Django 5.0.14 on 2026-04-03 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_announcements', '0001_initial'),
        ('platform_email_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformannouncement',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Optional; defaults to the «Platform announcement» system template when empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='platform_email_templates.platformemailtemplate'),
        ),
    ]
