# Generated by Django 5.0.14 on 2026-03-25 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_finance', '0047_journalentryattachment_document_management_fields'),
        ('tenant_grants', '0029_grant_financial_report_proxies'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('local', 'Local server (Django media)'), ('aws_s3', 'Amazon S3'), ('azure_blob', 'Azure Blob Storage'), ('sharepoint', 'Microsoft SharePoint'), ('google_drive', 'Google Drive'), ('dropbox', 'Dropbox')], db_index=True, default='local', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('config_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Storage provider configuration',
                'verbose_name_plural': 'Storage provider configurations',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('contract', 'Contract'), ('approval_memo', 'Approval memo'), ('bank_proof', 'Bank proof'), ('delivery_note', 'Delivery note'), ('request_letter', 'Request letter'), ('timesheet', 'Timesheet'), ('id_document', 'ID document'), ('cv', 'CV / resume'), ('donor_agreement', 'Donor agreement'), ('policy', 'Policy'), ('template', 'Template'), ('audit_evidence', 'Audit evidence'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search and filtering.', max_length=500)),
                ('tenant_key', models.CharField(blank=True, db_index=True, help_text='Tenant database alias for audit exports.', max_length=120)),
                ('module', models.CharField(blank=True, db_index=True, max_length=50)),
                ('submodule', models.CharField(blank=True, db_index=True, max_length=50)),
                ('linked_record_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('linked_record_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('voucher_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('employee_record_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('vendor_record_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_attachment', 'Pending attachment'), ('pending_approval', 'Pending approval'), ('ready_to_post', 'Ready to post'), ('approved', 'Approved'), ('posted', 'Posted / official record'), ('reversed', 'Reversed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=32)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Locked after posting; changes require versioning or reversal.')),
                ('storage_provider', models.CharField(blank=True, max_length=80)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_documents', to='tenant_grants.donor')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_documents', to='tenant_grants.grant')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_documents', to='tenant_grants.project')),
                ('source_journal_attachment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dm_document', to='tenant_finance.journalentryattachment')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_documents_uploaded', to='tenant_users.tenantuser')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_approvals_assigned', to='tenant_users.tenantuser')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_approvals_decided', to='tenant_users.tenantuser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='tenant_documents.document')),
            ],
            options={
                'ordering': ['document_id', 'step', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Metadata updated'), ('status', 'Status changed'), ('version', 'New version'), ('locked', 'Locked')], db_index=True, max_length=20)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_audit_events', to='tenant_users.tenantuser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='tenant_documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tenant_documents.documentcategory')),
            ],
            options={
                'verbose_name': 'Document category',
                'verbose_name_plural': 'Document categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='tenant_documents.documentcategory'),
        ),
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_app_label', models.CharField(db_index=True, max_length=100)),
                ('linked_model_name', models.CharField(db_index=True, help_text='Lowercase model name (e.g. grant, purchaserequisition).', max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('role', models.CharField(blank=True, help_text='e.g. primary, supporting, audit', max_length=40)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_links', to='tenant_documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='documents/versions/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_document_versions', to='tenant_users.tenantuser')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tenant_documents.document')),
            ],
            options={
                'ordering': ['-version', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['module', 'status'], name='tenant_docu_module_a8901e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['linked_record_type', 'linked_record_id'], name='tenant_docu_linked__de36be_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='tenant_docu_uploade_4bad7e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentlink',
            index=models.Index(
                fields=['linked_app_label', 'linked_model_name', 'object_id'],
                name='tenant_docu_link_idx',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version')},
        ),
    ]
