# Generated by Django 5.0.14 on 2026-03-25 11:58

import tenant_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_file_size_bytes', models.PositiveIntegerField(default=26214400, help_text='Maximum upload size in bytes.')),
                ('allowed_extensions', models.JSONField(default=tenant_documents.models._default_allowed_extensions_json, help_text='Lowercase extensions without dot, e.g. pdf, jpg.')),
                ('allowed_mime_types', models.JSONField(blank=True, default=tenant_documents.models._empty_json_list, help_text='Optional allowlist; empty means infer from extension only.', null=True)),
                ('require_category_for_library_upload', models.BooleanField(default=True, help_text='Standalone uploads must select a document category.')),
                ('block_duplicate_files', models.BooleanField(default=True, help_text='Reject uploads when SHA-256 matches an existing document in this tenant.')),
                ('enforce_workflow_transitions', models.BooleanField(default=True, help_text='Restrict status changes to allowed workflow edges.')),
                ('naming_convention_regex', models.CharField(blank=True, help_text='Optional full-match regex for original filename (empty = disabled).', max_length=500)),
                ('default_retention_years', models.PositiveSmallIntegerField(blank=True, help_text='Years from upload to retention_until (audit retention); blank = not auto-set.', null=True)),
                ('search_query_max_length', models.PositiveSmallIntegerField(default=200)),
                ('search_page_size_default', models.PositiveSmallIntegerField(default=40)),
                ('search_page_size_max', models.PositiveSmallIntegerField(default=100)),
                ('ngo_require_grant_when_entry_has_grant', models.BooleanField(default=True, help_text='Finance-linked documents must carry grant when journal entry has a grant.')),
                ('ngo_warn_missing_journal_document_category', models.BooleanField(default=True, help_text='Log audit warning when journal attachment has no NGO document category.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document policy configuration',
                'verbose_name_plural': 'Document policy configurations',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='file_sha256',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash for duplicate detection and audit integrity.', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata_synced_at',
            field=models.DateTimeField(blank=True, help_text='When transaction metadata was last synchronized into this record.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='retention_until',
            field=models.DateField(blank=True, db_index=True, help_text='Records retention deadline for NGO / statutory retention.', null=True),
        ),
        migrations.AlterField(
            model_name='documentauditevent',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Metadata updated'), ('status', 'Status changed'), ('version', 'New version'), ('locked', 'Locked'), ('metadata_sync', 'Metadata synchronized from transaction'), ('compliance', 'Compliance / validation')], db_index=True, max_length=20),
        ),
    ]
