"""
Django settings for sugna_core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-change-me'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    # Third-party admin theme (must come before django.contrib.admin)
    'jazzmin',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party
    'rest_framework',

    # Platform apps
    'tenants',
    'platform_dashboard',

    # Tenant-scoped apps (migrated into each tenant DB)
    'tenant_users',
    'rbac',
    'tenant_portal',
    'tenant_finance',
    'tenant_grants',
    'tenant_integrations',

    # Domain apps
    'ai_auditor',
]

JAZZMIN_SETTINGS = {
    "site_title": "Sugna Enterprise Suite Admin",
    "site_header": "Sugna Enterprise Suite",
    "site_brand": "Sugna",
    "welcome_sign": "Welcome to Sugna Enterprise Suite",
    "show_ui_builder": False,
    # Brand assets (these paths are relative to STATIC_URL)
    "site_logo": "img/sugna-logo-dark.png",
    "login_logo": "img/sugna-logo-dark.png",
    "login_logo_dark": "img/sugna-logo-light.png",
    # Custom CSS for brand colors and layout tweaks
    "custom_css": "css/sugna_admin.css",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar": "navbar-light",
    "navbar_fixed": True,
    "footer_fixed": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Resolve tenant by Host header (domain/subdomain)
    'sugna_core.middleware.TenantResolutionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sugna_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'platform_dashboard' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sugna_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "sugna_enterprise_suite",
        "USER": "postgres",
        "PASSWORD": "@@Hooyomacaan143",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

# Multi-tenant routing (DB-per-tenant). Add tenant module app labels here as you introduce them.
TENANT_APP_LABELS = (
    os.environ.get("TENANT_APP_LABELS", "").split(",")
    if os.environ.get("TENANT_APP_LABELS")
    else ["tenant_users", "rbac", "tenant_finance", "tenant_grants", "tenant_integrations"]
)
DATABASE_ROUTERS = ["sugna_core.db_router.TenantDatabaseRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

# Media files (uploaded assets such as tenant logos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Use BigAutoField across the project (enterprise default)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Platform dashboard: use admin login for auth
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/platform/'
