"""
Django settings for sugna_core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or os.environ.get("SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=false or 0 in production.
DEBUG = os.environ.get("DEBUG", "true").lower() in ("true", "1", "yes")

# Auto-run `migrate` on a tenant DB when code detects missing migrations (e.g. new columns).
# Defaults ON when DEBUG=true so local dev works without `migrate_tenant` after model changes.
# In production set DEBUG=false and keep TENANT_AUTO_MIGRATE unset or false.
_tam = os.environ.get("TENANT_AUTO_MIGRATE", "").strip().lower()
if _tam in ("true", "1", "yes"):
    TENANT_AUTO_MIGRATE = True
elif _tam in ("false", "0", "no"):
    TENANT_AUTO_MIGRATE = False
else:
    TENANT_AUTO_MIGRATE = DEBUG

def _split_csv(value: str) -> list[str]:
    return [x.strip() for x in (value or "").split(",") if x.strip()]


# Host header validation (400 Bad Request if the browser Host is not listed when DEBUG is False).
_env_hosts = _split_csv(os.environ.get("ALLOWED_HOSTS", ""))
_extra_hosts = _split_csv(os.environ.get("ALLOWED_HOSTS_EXTRA", ""))
if _env_hosts:
    ALLOWED_HOSTS = list(dict.fromkeys(_env_hosts + _extra_hosts))
elif DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    # Production: explicit ALLOWED_HOSTS env is recommended. If unset, allow primary Sugna domain
    # so https://sugnaerp.com does not 400 after deploy (health checks: localhost).
    ALLOWED_HOSTS = list(
        dict.fromkeys(
            ["sugnaerp.com", "www.sugnaerp.com", "127.0.0.1", "localhost"] + _extra_hosts
        )
    )

# If ALLOWED_HOSTS was set via env but omitted the public marketing domain, requests to
# https://sugnaerp.com still 400. Merge defaults in production unless strict mode is on.
_strict_hosts = os.environ.get("STRICT_ALLOWED_HOSTS_ONLY", "").lower() in ("1", "true", "yes")
_public_hosts = _split_csv(os.environ.get("SUGNA_PUBLIC_HOSTS", "sugnaerp.com,www.sugnaerp.com"))
if not DEBUG and not _strict_hosts and _public_hosts and ALLOWED_HOSTS != ["*"]:
    ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS + _public_hosts))

if os.environ.get("CSRF_TRUSTED_ORIGINS"):
    CSRF_TRUSTED_ORIGINS = _split_csv(os.environ["CSRF_TRUSTED_ORIGINS"])
elif not DEBUG:
    # HTTPS forms (login, contact) need trusted origins when behind TLS.
    CSRF_TRUSTED_ORIGINS = []
    for host in ALLOWED_HOSTS:
        if host == "*" or host.startswith("."):
            continue
        if host in ("127.0.0.1", "localhost"):
            CSRF_TRUSTED_ORIGINS.extend(
                [f"http://{host}", f"http://{host}:8000"]
            )
        else:
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
    if not CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = ["https://sugnaerp.com", "https://www.sugnaerp.com"]

if os.environ.get("USE_X_FORWARDED_HOST", "").lower() in ("1", "true", "yes"):
    USE_X_FORWARDED_HOST = True

# Production security hardening
# These should generally be enabled when DEBUG=false and the app is behind a TLS-terminating reverse proxy.
if not DEBUG:
    # Trust the proxy's TLS information (e.g. Nginx/Caddy: X-Forwarded-Proto: https)
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Ensure cookies are only sent over HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Enforce HTTPS + HSTS (configurable via env for safer rollout)
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "true").lower() in ("true", "1", "yes")
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get("SECURE_HSTS_INCLUDE_SUBDOMAINS", "true").lower() in ("true", "1", "yes")
    SECURE_HSTS_PRELOAD = os.environ.get("SECURE_HSTS_PRELOAD", "false").lower() in ("true", "1", "yes")


# Application definition

INSTALLED_APPS = [
    # Third-party admin theme (must come before django.contrib.admin)
    'jazzmin',

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Third-party
    'rest_framework',

    # Platform apps
    'tenants',
    'platform_dashboard',
    'website',
    'help_center',

    # Tenant-scoped apps (migrated into each tenant DB)
    'tenant_users',
    'rbac',
    'tenant_portal',
    'tenant_finance',
    'tenant_documents',
    'tenant_grants',
    'tenant_integrations',
    'tenant_audit_risk',

    # Domain apps (ai_auditor not yet implemented)
    "diagnostics",
]

JAZZMIN_SETTINGS = {
    "site_title": "Sugna Enterprise Suite Admin",
    "site_header": "Sugna Enterprise Suite",
    "site_brand": "Sugna",
    "welcome_sign": "Welcome to Sugna Enterprise Suite",
    "show_ui_builder": False,
    # Brand assets (these paths are relative to STATIC_URL)
    "site_logo": "img/sugna-logo-dark.png",
    "login_logo": "img/sugna-logo-dark.png",
    "login_logo_dark": "img/sugna-logo-light.png",
    # Custom CSS for brand colors and layout tweaks
    "custom_css": "css/sugna_admin.css",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "navbar": "navbar-light",
    "navbar_fixed": True,
    "footer_fixed": False,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # Resolve tenant by Host header (domain/subdomain)
    'sugna_core.middleware.TenantResolutionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Tenant-scoped RBAC context (permission cache)
    'tenant_portal.middleware_rbac.RBACContextMiddleware',
    'tenant_portal.middleware_erp_alerts.ErpAlertingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sugna_core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'platform_dashboard' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'django.contrib.humanize.templatetags.humanize',
                'tenant_portal.templatetags.erp_format',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tenant_portal.context_processors.org_settings',
                'tenant_portal.context_processors.smart_alerts',
                'tenant_portal.context_processors.erp_alerting',
            ],
        },
    },
]

WSGI_APPLICATION = 'sugna_core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Production: set DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT via environment.
_db_defaults = {
    "ENGINE": "django.db.backends.postgresql",
    "NAME": os.environ.get("DB_NAME", "sugna_enterprise_suite"),
    "USER": os.environ.get("DB_USER", "postgres"),
    "PASSWORD": os.environ.get("DB_PASSWORD", "@@Hooyomacaan143"),
    "HOST": os.environ.get("DB_HOST", "localhost"),
    "PORT": os.environ.get("DB_PORT", "5432"),
}
DATABASES = {"default": _db_defaults.copy()}
# Optional dev tenant DBs (same host/user/password as default)
_db_extra_tenants_default = "true" if DEBUG else "false"
if os.environ.get("DB_EXTRA_TENANTS", _db_extra_tenants_default).lower() in ("true", "1", "yes"):
    for alias, db_name in [("wardi", "wardi_db"), ("hurdo", "hurdo_db")]:
        DATABASES[alias] = {**_db_defaults.copy(), "NAME": db_name}

# Multi-tenant routing (DB-per-tenant). Models in these apps use the tenant DB at runtime and are
# migrated only on tenant databases (see TenantDatabaseRouter.allow_migrate). Platform DB (default)
# never receives tables for these apps — run `migrate` on default, then `migrate_all_tenants` or
# `migrate_tenant --tenant <slug>` so e.g. tenant_documents_document exists in each tenant schema.
TENANT_APP_LABELS = (
    os.environ.get("TENANT_APP_LABELS", "").split(",")
    if os.environ.get("TENANT_APP_LABELS")
    else ["tenant_users", "rbac", "tenant_finance", "tenant_documents", "tenant_grants", "tenant_integrations", "tenant_audit_risk"]
)
DATABASE_ROUTERS = ["sugna_core.db_router.TenantDatabaseRouter"]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (uploaded assets such as tenant logos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Audit Screening Upload: temporary storage only (files are deleted after review or TTL)
# Path separate from permanent document storage; not under MEDIA_ROOT for permanent uploads
SCREENING_UPLOAD_TEMP_ROOT = os.environ.get(
    "SCREENING_UPLOAD_TEMP_ROOT",
    str(BASE_DIR / "tmp" / "audit_screening"),
)
# Max age in hours before auto-deletion of temp files (default 48; only applies to files not yet finished)
SCREENING_UPLOAD_MAX_AGE_HOURS = int(os.environ.get("SCREENING_UPLOAD_MAX_AGE_HOURS", "48"))
# Max size per file (MB); 0 = no limit (large documents allowed)
SCREENING_UPLOAD_MAX_FILE_SIZE_MB = int(os.environ.get("SCREENING_UPLOAD_MAX_FILE_SIZE_MB", "0"))
# Max total size per session (MB); 0 = no limit
SCREENING_UPLOAD_MAX_SESSION_SIZE_MB = int(os.environ.get("SCREENING_UPLOAD_MAX_SESSION_SIZE_MB", "0"))

# Allow large request bodies for screening uploads (Django default is 2.5 MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(1024 * 1024 * 1024)))  # 1 GB default

# Use BigAutoField across the project (enterprise default)
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Website contact / demo forms: inbox for submissions (not shown on public pages — set only via environment).
WEBSITE_INBOUND_EMAIL = os.environ.get("WEBSITE_INBOUND_EMAIL", "").strip()

_default_from = os.environ.get("DEFAULT_FROM_EMAIL", "").strip()
if _default_from:
    DEFAULT_FROM_EMAIL = _default_from
else:
    DEFAULT_FROM_EMAIL = "Sugna Enterprise Suite <webmaster@localhost>"

SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Outbound SMTP (required in production to actually deliver mail; omitted in local dev → console backend).
_email_host = os.environ.get("EMAIL_HOST", "").strip()
if _email_host:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND",
        "django.core.mail.backends.smtp.EmailBackend",
    )
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("true", "1", "yes")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
else:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend",
    )

# Platform dashboard: use admin login for auth
LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/platform/'

# Diagnostics: automatic mode remediation (set True when running run_diagnostics from cron/Celery)
DIAGNOSTICS_AUTO_REMEDIATE = os.environ.get("DIAGNOSTICS_AUTO_REMEDIATE", "false").lower() in ("1", "true", "yes")
