# Generated by Django 5.0.14 on 2026-04-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable key for integrations (e.g. platform_announcement).', max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('system', 'System'), ('tenant', 'Tenant'), ('billing', 'Billing'), ('support', 'Support')], db_index=True, default='system', max_length=16)),
                ('subject', models.CharField(help_text='Supports {{ variable }} placeholders.', max_length=255)),
                ('body', models.TextField(help_text='Email body; supports {{ variable }} placeholders.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names documented for this template (e.g. tenant_name, amount).')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=16)),
                ('is_system', models.BooleanField(default=False, help_text='Built-in template; cannot be deleted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
