# Generated by Django 5.0.14 on 2026-03-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(help_text='Domain or subdomain used to route this tenant, e.g. ngo1.sugna.org (no protocol or path).', max_length=255, unique=True),
        ),
    ]
