# Generated by Django 5.0.14 on 2026-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_provisioning_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Enabled modules for this tenant (use TenantModule for metadata).', related_name='tenants', through='tenants.TenantModule', to='tenants.module'),
        ),
    ]
