# Generated by Django 5.0.14 on 2026-04-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_alter_tenant_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('trial', 'Trial'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', help_text='Display status for tenant lifecycle (Active, Trial, Pending, Suspended, Expired)', max_length=20),
        ),
        migrations.CreateModel(
            name='TenantBrandingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_full_name', models.CharField(blank=True, max_length=255)),
                ('display_short_name', models.CharField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, max_length=255, upload_to='tenant_branding/logos/%Y/%m/')),
                ('favicon', models.FileField(blank=True, max_length=255, upload_to='tenant_branding/favicons/%Y/%m/')),
                ('login_background', models.ImageField(blank=True, max_length=255, upload_to='tenant_branding/login_bg/%Y/%m/')),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('secondary_color', models.CharField(blank=True, max_length=20)),
                ('accent_color', models.CharField(blank=True, max_length=20)),
                ('print_header_logo', models.ImageField(blank=True, max_length=255, upload_to='tenant_branding/print/%Y/%m/')),
                ('print_header_organization_name', models.CharField(blank=True, max_length=255)),
                ('report_footer_text', models.CharField(blank=True, max_length=500)),
                ('welcome_text', models.TextField(blank=True)),
                ('post_login_mode', models.CharField(choices=[('auto', 'Auto (single module → workspace; else launcher)'), ('launcher', 'Always show module launcher'), ('default_module', 'Open default module workspace')], default='auto', max_length=32)),
                ('default_module_code', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding_profile', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant branding profile',
                'verbose_name_plural': 'Tenant branding profiles',
            },
        ),
    ]
