# Generated by Django 5.0.14 on 2026-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_branding_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbrandingprofile',
            name='text_on_primary_color',
            field=models.CharField(blank=True, help_text='Foreground on primary (top header). Auto if blank.', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantbrandingprofile',
            name='text_on_secondary_color',
            field=models.CharField(blank=True, help_text='Foreground on secondary (module nav bar). Auto if blank.', max_length=20),
        ),
    ]
