# Generated by Django 5.0.14 on 2026-03-10 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0001_initial'),
        ('tenant_grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenant_grants.grant'),
        ),
    ]
