# Generated by Django 5.0.14 on 2026-03-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0006_dimensions_cost_centers_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdimension',
            name='dimension_type',
            field=models.CharField(choices=[('department', 'Department'), ('project', 'Project'), ('location', 'Location'), ('program', 'Program'), ('grant', 'Grant'), ('activity', 'Activity'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('organization_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='org_settings/%Y/%m/')),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, help_text='Hex, e.g. #0078d4', max_length=20)),
                ('secondary_color', models.CharField(blank=True, help_text='Hex, e.g. #106ebe', max_length=20)),
                ('system_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='org_settings/%Y/%m/')),
                ('report_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='org_settings/%Y/%m/')),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='1-12, e.g. 7 for July')),
                ('fiscal_year_end_month', models.PositiveSmallIntegerField(default=12, help_text='1-12, e.g. 6 for June (year end)')),
                ('currency_format', models.CharField(blank=True, default='#,##0.00', max_length=40)),
                ('time_zone', models.CharField(blank=True, default='UTC', max_length=50)),
                ('invoice_prefix', models.CharField(blank=True, default='INV-', max_length=20)),
                ('payment_voucher_prefix', models.CharField(blank=True, default='PV-', max_length=20)),
                ('receipt_voucher_prefix', models.CharField(blank=True, default='RV-', max_length=20)),
                ('journal_prefix', models.CharField(blank=True, default='JV-', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_finance.currency')),
            ],
            options={
                'verbose_name_plural': 'Organization settings',
            },
        ),
    ]
