# Generated by Django 5.0.14 on 2026-03-15 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0007_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payee_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='tenant_finance.journalentry'),
        ),
    ]
