# Generated by Django 5.0.14 on 2026-03-15 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0008_disbursement_payment_status'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method for this voucher (e.g. cheque, bank_transfer, cash).', max_length=40),
        ),
        migrations.CreateModel(
            name='PaymentRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_at', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('payment_voucher', 'Payment Voucher'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='payment_voucher', max_length=30)),
                ('cheque_number', models.CharField(blank=True, max_length=60)),
                ('transfer_reference', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_users.tenantuser')),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_register_record', to='tenant_finance.journalentry')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
