# Generated by Django 5.0.14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_finance", "0010_accountcategory_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalentry",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of journal (manual, transaction, reversal, opening_balance, etc.)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="journal_type",
            field=models.CharField(
                blank=True,
                help_text="Adjustment, accrual, correction, opening_balance, reversal, etc. For manual journals.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("posted", "Posted"),
                    ("reversed", "Reversed"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
