# Generated by Django 5.0.14 on 2026-03-17 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0011_journal_entry_source_and_type'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTrailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_audit_logging', models.BooleanField(default=True)),
                ('track_voucher_edits', models.BooleanField(default=True)),
                ('track_approvals', models.BooleanField(default=True)),
                ('track_posting_actions', models.BooleanField(default=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit trail setting',
                'verbose_name_plural': 'Audit trail settings',
            },
        ),
        migrations.CreateModel(
            name='PostingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=120, unique=True)),
                ('can_create_voucher', models.BooleanField(default=True)),
                ('can_approve_voucher', models.BooleanField(default=False)),
                ('can_post_to_ledger', models.BooleanField(default=False)),
                ('max_posting_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('require_second_approval_above_amount', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posting permission',
                'verbose_name_plural': 'Posting permissions',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionReversalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_reversal', models.BooleanField(default=True)),
                ('allow_edit_before_posting', models.BooleanField(default=True)),
                ('allow_delete_before_approval', models.BooleanField(default=True)),
                ('require_reason_for_reversal', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction reversal & correction rule',
                'verbose_name_plural': 'Transaction reversal & correction rules',
            },
        ),
        migrations.AlterUniqueTogether(
            name='chartaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chartaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chartaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenant_users.tenantuser'),
        ),
        migrations.AddField(
            model_name='chartaccount',
            name='statement_type',
            field=models.CharField(blank=True, choices=[('balance_sheet', 'Balance Sheet'), ('income_expenditure', 'Income & Expenditure'), ('cash_flow', 'Cash Flow')], help_text='Must match account type: Asset/Liability/Equity → Balance Sheet; Income/Expense → Income & Expenditure.', max_length=30),
        ),
        migrations.AddField(
            model_name='chartaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='chartaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenant_users.tenantuser'),
        ),
        migrations.AddConstraint(
            model_name='chartaccount',
            constraint=models.UniqueConstraint(fields=('code',), name='uniq_chartaccount_code'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='fiscalperiod_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', models.F('end_date'))), name='fiscalyear_start_before_end'),
        ),
    ]
