# Generated by Django 5.0.14 on 2026-03-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0012_chart_account_audit_and_statement_type'),
        ('tenant_grants', '0021_project_donor_dates_grant_project_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDimensionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_finance.bankaccount')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_finance.costcenter')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_grants.donor')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_mapping', to='tenant_grants.project')),
            ],
            options={
                'verbose_name': 'Project dimension mapping',
                'verbose_name_plural': 'Project dimension mappings',
                'ordering': ['project__code'],
            },
        ),
    ]
