# Generated by Django 5.0.14 on 2026-03-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0013_project_donor_dates_grant_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdimensionmapping',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_finance.currency'),
        ),
    ]
