# Generated by Django 5.0.14 on 2026-03-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0014_project_grant_dimension_improvements'),
        ('tenant_grants', '0022_project_grant_dimension_improvements'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcontrolrule',
            name='allow_override',
            field=models.BooleanField(default=False, help_text='Allow authorized roles to override block at threshold.'),
        ),
        migrations.AddField(
            model_name='budgetcontrolrule',
            name='critical_at_percent',
            field=models.DecimalField(decimal_places=2, default=90, help_text='Critical threshold in percent (e.g. 90).', max_digits=5),
        ),
        migrations.AddField(
            model_name='budgetcontrolrule',
            name='override_roles',
            field=models.CharField(blank=True, help_text='Comma-separated role or permission codes allowed to override budget blocks.', max_length=255),
        ),
        migrations.AlterField(
            model_name='budgetcontrolrule',
            name='block_at_percent',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Block threshold in percent (e.g. 100).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='budgetcontrolrule',
            name='warn_at_percent',
            field=models.DecimalField(decimal_places=2, default=80, help_text='Warning threshold in percent (e.g. 80).', max_digits=5),
        ),
        migrations.CreateModel(
            name='BudgetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('warn', 'Warning'), ('block', 'Blocked'), ('override', 'Override')], max_length=20)),
                ('budget_line_code', models.CharField(blank=True, max_length=60)),
                ('account_code', models.CharField(blank=True, max_length=50)),
                ('utilization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('over_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('message', models.TextField(blank=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_events', to='tenant_finance.journalentry')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_grants.grant')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_grants.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_users.tenantuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
