# Generated by Django 5.0.14 on 2026-03-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0015_budget_control_rules_extensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcontrolrule',
            name='check_before_posting',
            field=models.BooleanField(default=True, help_text='If enabled, budget checks run automatically before posting transactions.'),
        ),
        migrations.AddField(
            model_name='budgetcontrolrule',
            name='include_commitments',
            field=models.BooleanField(default=True, help_text='If enabled, commitments (e.g. POs/PRs) are included when computing available budget.'),
        ),
        migrations.AlterField(
            model_name='budgetcontrolrule',
            name='override_roles',
            field=models.CharField(blank=True, help_text='Comma-separated role or permission codes allowed to override budget blocks (e.g. finance_manager, finance_director).', max_length=255),
        ),
    ]
