# Generated by Django 5.0.14 on 2026-03-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0016_budget_control_rule_flags_fixed2'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rate_type',
            field=models.CharField(choices=[('spot', 'Spot'), ('monthly', 'Monthly'), ('manual', 'Manual')], db_index=True, default='spot', max_length=20),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(blank=True, choices=[('central_bank', 'Central bank'), ('bank', 'Commercial bank'), ('manual', 'Manual')], default='manual', max_length=40),
        ),
    ]
