# Generated by Django 5.0.14 on 2026-03-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0017_exchange_rate_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('manual', 'Manual'), ('live_service', 'Live FX service')], default='manual', max_length=40),
        ),
    ]
