# Generated by Django 5.0.14 on 2026-03-17 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0018_exchange_rate_source_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentseries',
            name='fiscal_year',
            field=models.ForeignKey(
                to='tenant_finance.fiscalyear',
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
                related_name='document_series',
                help_text='Optional: limit this series to a specific fiscal year.',
            ),
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='name',
            field=models.CharField(max_length=120, default='Legacy mapping'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='transaction_type',
            field=models.CharField(
                max_length=40,
                choices=[
                    ('receipt', 'Receipt'),
                    ('payment', 'Payment'),
                    ('journal', 'Journal'),
                    ('transfer', 'Transfer'),
                ],
                default='receipt',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='default_debit_account',
            field=models.ForeignKey(
                to='tenant_finance.chartaccount',
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
                related_name='+',
            ),
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='default_credit_account',
            field=models.ForeignKey(
                to='tenant_finance.chartaccount',
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
                related_name='+',
            ),
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='apply_dimension',
            field=models.CharField(
                max_length=40,
                choices=[
                    ('none', 'None'),
                    ('project', 'Project'),
                    ('grant', 'Grant'),
                    ('cost_center', 'Cost Center'),
                ],
                default='none',
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='status',
            field=models.CharField(
                max_length=20,
                choices=[('active', 'Active'), ('inactive', 'Inactive')],
                default='active',
                db_index=True,
            ),
        ),
        migrations.AddField(
            model_name='defaultaccountmapping',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
