# Generated by Django 5.0.14 on 2026-03-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0019_tenant_finance_manual_defaults'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE tenant_finance_documentseries
            ADD COLUMN IF NOT EXISTS fiscal_year_id integer NULL;
            """,
            reverse_sql="""
            -- Intentionally left blank: do not drop fiscal_year_id on reverse.
            """,
        ),
    ]
