# Generated by Django 5.0.14 on 2026-03-19 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0031_accounting_period_controls'),
        ('tenant_grants', '0023_project_grant_period_extensions'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantComplianceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('warn', 'Warning'), ('block', 'Blocked')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('missing_documents', models.BooleanField(default=False)),
                ('admin_ceiling_breach', models.BooleanField(default=False)),
                ('ineligible_category', models.BooleanField(default=False)),
                ('outside_grant_period', models.BooleanField(default=False)),
                ('procurement_issue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grant compliance event',
                'verbose_name_plural': 'Grant compliance events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name for this compliance rule.', max_length=160)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('reporting_period_start', models.DateField(blank=True, help_text='Start date of the donor reporting period for this rule.', null=True)),
                ('reporting_period_end', models.DateField(blank=True, help_text='End date of the donor reporting period for this rule.', null=True)),
                ('reminder_days_before_deadline', models.PositiveIntegerField(default=5, help_text='Days before reporting period end when reminders should be sent.')),
                ('maximum_admin_cost_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional admin cost ceiling as % of total grant.', max_digits=5, null=True)),
                ('require_attachments', models.BooleanField(default=False)),
                ('require_procurement_compliance', models.BooleanField(default=False)),
                ('require_budget_check', models.BooleanField(default=True)),
                ('allow_posting_outside_grant_period', models.BooleanField(default=False)),
                ('require_additional_approval', models.BooleanField(default=False)),
                ('additional_approval_role', models.CharField(blank=True, max_length=120)),
                ('mode', models.CharField(choices=[('warn', 'Warning only'), ('block', 'Block on violation')], default='block', help_text='Warning mode allows posting with warning; Block mode prevents posting.', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grant compliance rule',
                'verbose_name_plural': 'Grant compliance rules',
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InterFundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('from_fund_type', models.CharField(choices=[('grant', 'Grant'), ('project', 'Project'), ('donor_fund', 'Donor Fund'), ('unrestricted', 'Unrestricted Fund'), ('co_funding', 'Co-funding')], max_length=40)),
                ('to_fund_type', models.CharField(choices=[('grant', 'Grant'), ('project', 'Project'), ('donor_fund', 'Donor Fund'), ('unrestricted', 'Unrestricted Fund'), ('co_funding', 'Co-funding')], max_length=40)),
                ('from_fund_code', models.CharField(max_length=80)),
                ('to_fund_code', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inter-fund transfer',
                'verbose_name_plural': 'Inter-fund transfers',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InterFundTransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('from_fund_type', models.CharField(choices=[('grant', 'Grant'), ('project', 'Project'), ('donor_fund', 'Donor Fund'), ('unrestricted', 'Unrestricted Fund'), ('co_funding', 'Co-funding')], max_length=40)),
                ('to_fund_type', models.CharField(choices=[('grant', 'Grant'), ('project', 'Project'), ('donor_fund', 'Donor Fund'), ('unrestricted', 'Unrestricted Fund'), ('co_funding', 'Co-funding')], max_length=40)),
                ('specific_from_fund_code', models.CharField(blank=True, help_text='Optional fund identifier/code for the source fund.', max_length=80)),
                ('specific_to_fund_code', models.CharField(blank=True, help_text='Optional fund identifier/code for the destination fund.', max_length=80)),
                ('allow_transfer', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=True)),
                ('approval_role', models.CharField(blank=True, help_text='Role/title required to approve this transfer (e.g. Finance Manager).', max_length=120)),
                ('require_reason', models.BooleanField(default=True)),
                ('maximum_transfer_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap per transfer; leave blank for no explicit limit.', max_digits=18, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inter-fund transfer rule',
                'verbose_name_plural': 'Inter-fund transfer rules',
                'ordering': ['-effective_from', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='approvalworkflow',
            options={'ordering': ['document_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='defaultaccountmapping',
            options={'ordering': ['transaction_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='documentseries',
            options={'ordering': ['document_type', 'prefix'], 'verbose_name': 'Document series', 'verbose_name_plural': 'Document series'},
        ),
        migrations.AlterModelOptions(
            name='postingrule',
            options={'ordering': ['transaction_type', 'name']},
        ),
        migrations.RenameIndex(
            model_name='budgetoverriderequest',
            new_name='tenant_fina_entry_i_f27a2a_idx',
            old_name='tenant_fina_entry_id_ef5d0c_idx',
        ),
        migrations.RemoveField(
            model_name='documentseries',
            name='year_format',
        ),
        migrations.RemoveField(
            model_name='postingrule',
            name='voucher_type',
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='apply_dimension',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('project', 'Project'), ('grant', 'Grant'), ('cost_center', 'Cost Center')], default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='transaction_type',
            field=models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('journal', 'Journal'), ('transfer', 'Transfer')], default='receipt', max_length=40),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='document_type',
            field=models.CharField(choices=[('payment_voucher', 'Payment Voucher'), ('receipt_voucher', 'Receipt Voucher'), ('staff_advance', 'Staff Advance'), ('bank_transfer', 'Bank Transfer'), ('journal_entry', 'Journal Entry')], help_text='Transaction type this workflow applies to.', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultaccountmapping',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_finance.chartaccount'),
        ),
        migrations.AlterField(
            model_name='documentseries',
            name='document_type',
            field=models.CharField(choices=[('payment_voucher', 'Payment Voucher'), ('receipt_voucher', 'Receipt Voucher'), ('journal', 'Journal Entry'), ('disbursement', 'Disbursement'), ('vendor_payment', 'Vendor Payment'), ('grant_receipt', 'Grant Receipt')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='defaultaccountmapping',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_defaultaccountmapping_name'),
        ),
        migrations.AddConstraint(
            model_name='postingrule',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_postingrule_name'),
        ),
        migrations.AddField(
            model_name='grantcomplianceevent',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_grants.donor'),
        ),
        migrations.AddField(
            model_name='grantcomplianceevent',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_compliance_events', to='tenant_finance.journalentry'),
        ),
        migrations.AddField(
            model_name='grantcomplianceevent',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenant_grants.grant'),
        ),
        migrations.AddField(
            model_name='grantcompliancerule',
            name='allowed_account_categories',
            field=models.ManyToManyField(blank=True, related_name='grant_compliance_allowed_rules', to='tenant_finance.accountcategory'),
        ),
        migrations.AddField(
            model_name='grantcompliancerule',
            name='disallowed_account_categories',
            field=models.ManyToManyField(blank=True, related_name='grant_compliance_disallowed_rules', to='tenant_finance.accountcategory'),
        ),
        migrations.AddField(
            model_name='grantcompliancerule',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_rules', to='tenant_grants.donor'),
        ),
        migrations.AddField(
            model_name='grantcompliancerule',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_rules', to='tenant_grants.grant'),
        ),
        migrations.AddField(
            model_name='grantcompliancerule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compliance_rules', to='tenant_grants.project'),
        ),
        migrations.AddField(
            model_name='grantcomplianceevent',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tenant_finance.grantcompliancerule'),
        ),
        migrations.AddField(
            model_name='interfundtransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interfund_transfers_approved', to='tenant_users.tenantuser'),
        ),
        migrations.AddField(
            model_name='interfundtransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interfund_transfers_created', to='tenant_users.tenantuser'),
        ),
        migrations.AddField(
            model_name='interfundtransfer',
            name='posted_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfund_transfers', to='tenant_finance.journalentry'),
        ),
        migrations.AddField(
            model_name='interfundtransferrule',
            name='transfer_account',
            field=models.ForeignKey(help_text='Clearing/transfer account to use for inter-fund postings.', on_delete=django.db.models.deletion.PROTECT, related_name='interfund_rules', to='tenant_finance.chartaccount'),
        ),
        migrations.AddField(
            model_name='interfundtransfer',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='tenant_finance.interfundtransferrule'),
        ),
        migrations.AddConstraint(
            model_name='grantcompliancerule',
            constraint=models.UniqueConstraint(fields=('grant', 'name'), name='uniq_grantcompliancerule_grant_name'),
        ),
    ]
