# Generated by Django 5.0.14 on 2026-03-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0041_journal_workflow_audit'),
        ('tenant_grants', '0023_project_grant_period_extensions'),
        ('tenant_users', '0004_add_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfundtransfer',
            name='from_bank_account',
            field=models.ForeignKey(blank=True, help_text="Source bank; GL account is bank's linked chart account.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interfund_transfers_out', to='tenant_finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='interfundtransfer',
            name='from_project',
            field=models.ForeignKey(blank=True, help_text='Source project when using project/bank workflow.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interfund_transfers_from', to='tenant_grants.project'),
        ),
        migrations.AlterField(
            model_name='interfundtransfer',
            name='to_bank_account',
            field=models.ForeignKey(blank=True, help_text="Destination bank; GL account is bank's linked chart account.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interfund_transfers_in', to='tenant_finance.bankaccount'),
        ),
        migrations.AlterField(
            model_name='interfundtransfer',
            name='to_project',
            field=models.ForeignKey(blank=True, help_text='Destination project when using project/bank workflow.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interfund_transfers_to', to='tenant_grants.project'),
        ),
        migrations.AlterField(
            model_name='interfundtransfer',
            name='transfer_no',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-assigned transfer number (e.g. IFT-2025-000042).', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='adjustment_type',
            field=models.CharField(blank=True, choices=[('accrual', 'Accrual'), ('prepayment_adjustment', 'Prepayment adjustment'), ('reclassification', 'Reclassification'), ('correction', 'Correction'), ('depreciation', 'Depreciation'), ('provision', 'Provision'), ('year_end_adjustment', 'Year-end adjustment'), ('audit_adjustment', 'Audit adjustment'), ('other', 'Other')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the journal for approval.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_submitted', to='tenant_users.tenantuser'),
        ),
        migrations.AlterField(
            model_name='recurringjournal',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional; template completes after last run in range.', null=True),
        ),
        migrations.AlterField(
            model_name='recurringjournalline',
            name='grant',
            field=models.ForeignKey(blank=True, help_text='Optional project/grant dimension for NGO reporting.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_journal_lines', to='tenant_grants.grant'),
        ),
    ]
