# Generated by Django 5.0.14 on 2026-03-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0042_alter_interfundtransfer_from_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='posting_date',
            field=models.DateField(blank=True, help_text='GL posting date (determines fiscal year and accounting period for posting). Defaults to journal date when omitted.', null=True),
        ),
        migrations.AlterField(
            model_name='transactionreversalrule',
            name='authorized_roles_for_cross_period_reversal',
            field=models.CharField(blank=True, help_text='Comma-separated role or permission codes allowed to perform cross-fiscal-year reversals.', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactionreversalrule',
            name='prevent_cross_period_reversal',
            field=models.BooleanField(default=True, help_text='If enabled, reversals cannot move amounts across fiscal years unless explicitly authorized.'),
        ),
    ]
