# Generated by Django 5.0.14 on 2026-03-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_finance", "0044_journalline_project_budget_workplan"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[],
            options={
                "verbose_name": "Journal entry line",
                "verbose_name_plural": "Journal entry lines",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tenant_finance.journalline",),
        ),
    ]
