# Generated by Django 5.0.14 on 2026-03-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0049_audittrailsetting_receipt_approval_policy'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='journalline',
            new_name='tenant_fina_project_e8bf6a_idx',
            old_name='journalline_pbl_idx',
        ),
        migrations.RenameIndex(
            model_name='journalline',
            new_name='tenant_fina_workpla_387164_idx',
            old_name='journalline_wa_idx',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='receipt_stream',
            field=models.CharField(blank=True, choices=[('grant_funding', 'Grant funding'), ('other_income', 'Other income'), ('cashbook', 'Cashbook')], db_index=True, help_text='Receipt voucher stream: grant funding vs other income vs cashbook.', max_length=20),
        ),
    ]
