# Generated by Django 5.0.14 on 2026-03-27 18:23

from django.db import migrations, models


def forwards_normalize_account_class(apps, schema_editor):
    ChartAccount = apps.get_model("tenant_finance", "ChartAccount")
    AccountCategory = apps.get_model("tenant_finance", "AccountCategory")
    pairs = [
        ("asset", "ASSET"),
        ("liability", "LIABILITY"),
        ("equity", "EQUITY"),
        ("income", "INCOME"),
        ("expense", "EXPENSE"),
    ]
    for old, new in pairs:
        ChartAccount.objects.filter(type__iexact=old).exclude(type=new).update(type=new)
        AccountCategory.objects.filter(category_type__iexact=old).exclude(category_type=new).update(
            category_type=new
        )


def backwards_restore_lowercase(apps, schema_editor):
    ChartAccount = apps.get_model("tenant_finance", "ChartAccount")
    AccountCategory = apps.get_model("tenant_finance", "AccountCategory")
    pairs = [
        ("ASSET", "asset"),
        ("LIABILITY", "liability"),
        ("EQUITY", "equity"),
        ("INCOME", "income"),
        ("EXPENSE", "expense"),
    ]
    for new, old in pairs:
        ChartAccount.objects.filter(type=new).update(type=old)
        AccountCategory.objects.filter(category_type=new).update(category_type=old)


class Migration(migrations.Migration):

    dependencies = [
        ("tenant_finance", "0053_journalentry_payee_reference"),
    ]

    operations = [
        migrations.RunPython(forwards_normalize_account_class, backwards_restore_lowercase),
        migrations.AlterField(
            model_name="accountcategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                ],
                help_text="Account class; must align with statement type (Balance Sheet vs Income & Expenditure).",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chartaccount",
            name="type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("INCOME", "Income"),
                    ("EXPENSE", "Expense"),
                ],
                max_length=20,
            ),
        ),
    ]
