# Generated by Django 5.0.14 on 2026-03-28 05:12

from django.db import migrations, models


def forwards_bank_gl_types_and_allow_posting(apps, schema_editor):
    ChartAccount = apps.get_model("tenant_finance", "ChartAccount")
    db = schema_editor.connection.alias
    ST_BALANCE = "balance_sheet"

    # Common corrupted value (truncated "ASSET")
    ChartAccount.objects.using(db).filter(type__iexact="sset").update(type="ASSET")

    bank_root = ChartAccount.objects.using(db).filter(code="1200").first()
    if bank_root:
        ChartAccount.objects.using(db).filter(parent_id=bank_root.pk).exclude(type="ASSET").update(
            type="ASSET",
            statement_type=ST_BALANCE,
        )

    for acc in ChartAccount.objects.using(db).all().iterator():
        has_ch = ChartAccount.objects.using(db).filter(parent_id=acc.pk).exists()
        ChartAccount.objects.using(db).filter(pk=acc.pk).update(allow_posting=not has_ch)


def backwards_allow_posting_all_true(apps, schema_editor):
    ChartAccount = apps.get_model("tenant_finance", "ChartAccount")
    db = schema_editor.connection.alias
    ChartAccount.objects.using(db).all().update(allow_posting=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_finance', '0054_normalize_account_class_uppercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccount',
            name='allow_posting',
            field=models.BooleanField(db_index=True, default=True, help_text='False for control or summary accounts (accounts with sub-accounts). True for leaf accounts that may receive journal postings.'),
        ),
        migrations.RunPython(forwards_bank_gl_types_and_allow_posting, backwards_allow_posting_all_true),
        migrations.AlterField(
            model_name='financialdimension',
            name='dimension_type',
            field=models.CharField(choices=[('department', 'Department'), ('project', 'Project'), ('location', 'Location'), ('program', 'Program'), ('grant', 'Grant'), ('activity', 'Activity'), ('classification', 'Classification'), ('custom', 'Custom')], max_length=20),
        ),
    ]
