# Generated by Django 5.0.14 on 2026-03-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant')], db_index=True, max_length=20)),
                ('tenant_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_slug', models.CharField(blank=True, max_length=100)),
                ('check_type', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('timeout', 'Timeout'), ('partial', 'Partial')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Diagnostic check run',
                'verbose_name_plural': 'Diagnostic check runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('remediating', 'Remediating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant')], default='platform', max_length=20)),
                ('tenant_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_slug', models.CharField(blank=True, max_length=100)),
                ('root_cause_summary', models.TextField(blank=True)),
                ('suggested_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=80)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('tenant_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RemediationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=80, unique=True)),
                ('allowed', models.BooleanField(default=True)),
                ('require_approval', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Remediation policies',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='diagnostics.diagnosticcheckrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RemediationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(db_index=True, max_length=80)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('skipped', 'Skipped')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_logs', to='diagnostics.incident')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
