# Generated by Django 5.0.14 on 2026-03-15 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Help categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_user_id', models.PositiveIntegerField(blank=True, help_text="ID of the user in the tenant's DB (TenantUser.id).", null=True)),
                ('user_email', models.CharField(max_length=254)),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('support_notes', models.TextField(blank=True, help_text='Internal notes (not shown to user).')),
                ('support_response', models.TextField(blank=True, help_text='Response to the user.')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('guide', 'User guide'), ('module_help', 'Module help'), ('faq', 'FAQ'), ('video', 'Video tutorial'), ('support_contact', 'Support contact')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('body', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='For video tutorials.', max_length=500)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_role', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=60)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='help_center.helpcategory')),
            ],
            options={
                'verbose_name_plural': 'Help contents',
                'ordering': ['display_order', 'title'],
                'unique_together': {('category', 'slug')},
            },
        ),
    ]
