# Generated by Django 5.0.14 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rbac", "0002_role_is_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="role_type",
            field=models.CharField(
                choices=[("financial", "Financial"), ("operational", "Operational"), ("admin", "Admin")],
                db_index=True,
                default="operational",
                max_length=20,
            ),
        ),
    ]

