# Generated by Django 5.0.14 on 2026-04-01 07:58

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('payer_name', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('progress', 'Progress'), ('soap_s', 'SOAP — Subjective'), ('soap_o', 'SOAP — Objective'), ('soap_a', 'SOAP — Assessment'), ('soap_p', 'SOAP — Plan'), ('other', 'Other')], default='progress', max_length=20)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('author_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_notes', to='tenant_hospital.provider')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to='tenant_hospital.encounter')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=20)),
                ('ordered_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='tenant_hospital.encounter')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders_ordered', to='tenant_hospital.provider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='tenant_hospital.patient')),
            ],
            options={
                'ordering': ['-ordered_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('test_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resulted', 'Resulted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_text', models.TextField(blank=True)),
                ('resulted_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_hospital.laborder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(db_index=True, max_length=80)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='tenant_hospital.patient')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_policies', to='tenant_hospital.insuranceplan')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PatientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(db_index=True, default='USD', max_length=3)),
                ('issued_at', models.DateTimeField(db_index=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='tenant_hospital.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenant_hospital.patient')),
            ],
            options={
                'ordering': ['-issued_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], db_index=True, default='ordered', max_length=20)),
                ('ordered_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders', to='tenant_hospital.encounter')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_orders_ordered', to='tenant_hospital.provider')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_orders', to='tenant_hospital.patient')),
            ],
            options={
                'ordering': ['-ordered_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('dose', models.CharField(blank=True, max_length=120)),
                ('route', models.CharField(blank=True, help_text='e.g. PO, IV', max_length=80)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('quantity', models.CharField(blank=True, max_length=80)),
                ('instructions', models.TextField(blank=True)),
                ('pharmacy_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_hospital.pharmacyorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, help_text='bpm', null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, help_text='%', null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='tenant_hospital.encounter')),
            ],
            options={
                'ordering': ['-recorded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('floor', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards', to='tenant_hospital.department')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_label', models.CharField(blank=True, max_length=40)),
                ('bed_label', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='tenant_hospital.ward')),
            ],
            options={
                'ordering': ['ward', 'room_label', 'bed_label'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged')], db_index=True, default='active', max_length=20)),
                ('admitted_at', models.DateTimeField(db_index=True)),
                ('discharged_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='tenant_hospital.patient')),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='tenant_hospital.bed')),
            ],
            options={
                'ordering': ['-admitted_at', 'id'],
                'indexes': [models.Index(fields=['status', 'admitted_at'], name='tenant_hosp_status_59b80d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='bed',
            constraint=models.UniqueConstraint(fields=('ward', 'room_label', 'bed_label'), name='uniq_tenant_hospital_bed_room'),
        ),
    ]
